name: CI
on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies
        run: npm install

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gatsby build --prefix-paths
          npx gh-pages -d public -b master -u "github-actions-bot <support+actions@github.com>"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}